package com.springmvc.generator.pojo;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataanalyst.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataanalyst.companyFullName
     *
     * @mbggenerated
     */
    private String companyfullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataanalyst.companyId
     *
     * @mbggenerated
     */
    private String companyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataanalyst.companyLabelList
     *
     * @mbggenerated
     */
    private String companylabellist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataanalyst.companyShortName
     *
     * @mbggenerated
     */
    private String companyshortname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataanalyst.companySize
     *
     * @mbggenerated
     */
    private String companysize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataanalyst.businessZones
     *
     * @mbggenerated
     */
    private String businesszones;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataanalyst.firstType
     *
     * @mbggenerated
     */
    private String firsttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataanalyst.secondType
     *
     * @mbggenerated
     */
    private String secondtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataanalyst.education
     *
     * @mbggenerated
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataanalyst.industryField
     *
     * @mbggenerated
     */
    private String industryfield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataanalyst.positionId
     *
     * @mbggenerated
     */
    private String positionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataanalyst.positionAdvantage
     *
     * @mbggenerated
     */
    private String positionadvantage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataanalyst.positionName
     *
     * @mbggenerated
     */
    private String positionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataanalyst.positionLables
     *
     * @mbggenerated
     */
    private String positionlables;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataanalyst.salary
     *
     * @mbggenerated
     */
    private String salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataanalyst.workYear
     *
     * @mbggenerated
     */
    private String workyear;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataanalyst.city
     *
     * @return the value of dataanalyst.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataanalyst.city
     *
     * @param city the value for dataanalyst.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataanalyst.companyFullName
     *
     * @return the value of dataanalyst.companyFullName
     *
     * @mbggenerated
     */
    public String getCompanyfullname() {
        return companyfullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataanalyst.companyFullName
     *
     * @param companyfullname the value for dataanalyst.companyFullName
     *
     * @mbggenerated
     */
    public void setCompanyfullname(String companyfullname) {
        this.companyfullname = companyfullname == null ? null : companyfullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataanalyst.companyId
     *
     * @return the value of dataanalyst.companyId
     *
     * @mbggenerated
     */
    public String getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataanalyst.companyId
     *
     * @param companyid the value for dataanalyst.companyId
     *
     * @mbggenerated
     */
    public void setCompanyid(String companyid) {
        this.companyid = companyid == null ? null : companyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataanalyst.companyLabelList
     *
     * @return the value of dataanalyst.companyLabelList
     *
     * @mbggenerated
     */
    public String getCompanylabellist() {
        return companylabellist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataanalyst.companyLabelList
     *
     * @param companylabellist the value for dataanalyst.companyLabelList
     *
     * @mbggenerated
     */
    public void setCompanylabellist(String companylabellist) {
        this.companylabellist = companylabellist == null ? null : companylabellist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataanalyst.companyShortName
     *
     * @return the value of dataanalyst.companyShortName
     *
     * @mbggenerated
     */
    public String getCompanyshortname() {
        return companyshortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataanalyst.companyShortName
     *
     * @param companyshortname the value for dataanalyst.companyShortName
     *
     * @mbggenerated
     */
    public void setCompanyshortname(String companyshortname) {
        this.companyshortname = companyshortname == null ? null : companyshortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataanalyst.companySize
     *
     * @return the value of dataanalyst.companySize
     *
     * @mbggenerated
     */
    public String getCompanysize() {
        return companysize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataanalyst.companySize
     *
     * @param companysize the value for dataanalyst.companySize
     *
     * @mbggenerated
     */
    public void setCompanysize(String companysize) {
        this.companysize = companysize == null ? null : companysize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataanalyst.businessZones
     *
     * @return the value of dataanalyst.businessZones
     *
     * @mbggenerated
     */
    public String getBusinesszones() {
        return businesszones;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataanalyst.businessZones
     *
     * @param businesszones the value for dataanalyst.businessZones
     *
     * @mbggenerated
     */
    public void setBusinesszones(String businesszones) {
        this.businesszones = businesszones == null ? null : businesszones.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataanalyst.firstType
     *
     * @return the value of dataanalyst.firstType
     *
     * @mbggenerated
     */
    public String getFirsttype() {
        return firsttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataanalyst.firstType
     *
     * @param firsttype the value for dataanalyst.firstType
     *
     * @mbggenerated
     */
    public void setFirsttype(String firsttype) {
        this.firsttype = firsttype == null ? null : firsttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataanalyst.secondType
     *
     * @return the value of dataanalyst.secondType
     *
     * @mbggenerated
     */
    public String getSecondtype() {
        return secondtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataanalyst.secondType
     *
     * @param secondtype the value for dataanalyst.secondType
     *
     * @mbggenerated
     */
    public void setSecondtype(String secondtype) {
        this.secondtype = secondtype == null ? null : secondtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataanalyst.education
     *
     * @return the value of dataanalyst.education
     *
     * @mbggenerated
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataanalyst.education
     *
     * @param education the value for dataanalyst.education
     *
     * @mbggenerated
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataanalyst.industryField
     *
     * @return the value of dataanalyst.industryField
     *
     * @mbggenerated
     */
    public String getIndustryfield() {
        return industryfield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataanalyst.industryField
     *
     * @param industryfield the value for dataanalyst.industryField
     *
     * @mbggenerated
     */
    public void setIndustryfield(String industryfield) {
        this.industryfield = industryfield == null ? null : industryfield.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataanalyst.positionId
     *
     * @return the value of dataanalyst.positionId
     *
     * @mbggenerated
     */
    public String getPositionid() {
        return positionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataanalyst.positionId
     *
     * @param positionid the value for dataanalyst.positionId
     *
     * @mbggenerated
     */
    public void setPositionid(String positionid) {
        this.positionid = positionid == null ? null : positionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataanalyst.positionAdvantage
     *
     * @return the value of dataanalyst.positionAdvantage
     *
     * @mbggenerated
     */
    public String getPositionadvantage() {
        return positionadvantage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataanalyst.positionAdvantage
     *
     * @param positionadvantage the value for dataanalyst.positionAdvantage
     *
     * @mbggenerated
     */
    public void setPositionadvantage(String positionadvantage) {
        this.positionadvantage = positionadvantage == null ? null : positionadvantage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataanalyst.positionName
     *
     * @return the value of dataanalyst.positionName
     *
     * @mbggenerated
     */
    public String getPositionname() {
        return positionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataanalyst.positionName
     *
     * @param positionname the value for dataanalyst.positionName
     *
     * @mbggenerated
     */
    public void setPositionname(String positionname) {
        this.positionname = positionname == null ? null : positionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataanalyst.positionLables
     *
     * @return the value of dataanalyst.positionLables
     *
     * @mbggenerated
     */
    public String getPositionlables() {
        return positionlables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataanalyst.positionLables
     *
     * @param positionlables the value for dataanalyst.positionLables
     *
     * @mbggenerated
     */
    public void setPositionlables(String positionlables) {
        this.positionlables = positionlables == null ? null : positionlables.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataanalyst.salary
     *
     * @return the value of dataanalyst.salary
     *
     * @mbggenerated
     */
    public String getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataanalyst.salary
     *
     * @param salary the value for dataanalyst.salary
     *
     * @mbggenerated
     */
    public void setSalary(String salary) {
        this.salary = salary == null ? null : salary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataanalyst.workYear
     *
     * @return the value of dataanalyst.workYear
     *
     * @mbggenerated
     */
    public String getWorkyear() {
        return workyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataanalyst.workYear
     *
     * @param workyear the value for dataanalyst.workYear
     *
     * @mbggenerated
     */
    public void setWorkyear(String workyear) {
        this.workyear = workyear == null ? null : workyear.trim();
    }
}