package com.springmvc.generator.mapper;

import com.springmvc.generator.pojo.Student;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dataanalyst
     *
     * @mbggenerated
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dataanalyst
     *
     * @mbggenerated
     */
    int insertSelective(Student record);
}