spring:
#  datasource:
#    url: jdbc:mysql://118.24.122.203:3306/tyb?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: xzm348701
#    driver-class-name: com.mysql.jdbc.Driver
#    #最大活跃数
#    maxActive: 20
#    #初始化数量
#    initialSize: 1
#    #最大连接等待超时时间
#    maxWait: 60000
#    #打开PSCache，并且指定每个连接PSCache的大小
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
#    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 1 from dual
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
#    filters: stat, wall, log4j
#  jpa:
#    database: MYSQL
#    show-sql: true
#  #Hibernate ddl auto (validate|create|create-drop|update)
#    hibernate:
#      ddl-auto: update
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
  #配置redis数据库连接
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 20
      min-idle: 1
      max-active: 20
      max-wait: 60000
    database: 0   #默认是索引为的0的数据库
  # thymeleaf 模板引擎
  thymeleaf:
          cache: false
          prefix: classpath:/templates/
          suffix: .html
#          mode: LEGACYHTML5
          encoding: UTF-8
          content-type: text/html
  # 指定静态资源的路径
  resources:
        static-locations: classpath:/static/,classpath:/templates/
#  配置环境文件
  profiles:
    active: test

#springMVC 配置路径
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
#      views-name:

#mybatis:
##   mapper-locations: classpath:mapper/*.xml
##   mapperLocations: classpath:mapper/**/*.xml
#    mapper-Locations: classpath:mapper/**/*.xml
#    type-aliases-package: com.xzm.poji
#    configLocation: classpath:mybatis.xml
#pagehelper分页插件配置
pagehelper:
    helperDialect: mysql
    reasonable: false
    params: count=countSql
    page-size-zero: true
    support-methods-arguments: true
#tyb:
#    # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】新消息
#    jwt:
#        # 加密秘钥
#        secret: f4e2e52034348f86b67cde581c0f9eb5[www.renren.io]
#        # token有效时长，7天，单位秒
#        expire: 604800
#        header: token

# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8084
    connection-timeout: 5000
#   context-path: /tyb
# 配置全局url前缀
